### ISSUE TITLE
TypeError: Incorrect value for stdio stream: inherit

### ISSUE THREAD

**Issue by binggg** [fraserxu/electron-pdf#1]
``` bash
binggg@BINGGG-PC ~
$ electron-pdf --help

child_process.js:901
      throw new TypeError('Incorrect value for stdio stream: ' + stdio);
            ^
TypeError: Incorrect value for stdio stream: inherit
    at child_process.js:901:13
    at Array.reduce (native)
    at ChildProcess.spawn (child_process.js:856:17)
    at exports.spawn (child_process.js:715:9)
    at runElectron (c:\Users\binggg\AppData\Roaming\npm\node_modules\electron-pdf\cli.js:24:18)
    at c:\Users\binggg\AppData\Roaming\npm\node_modules\electron-pdf\cli.js:17:28
    at c:\Users\binggg\AppData\Roaming\npm\node_modules\electron-pdf\node_modules\which\which.js:81:18
    at Object.oncomplete (fs.js:107:15)
```

**Comment by fraserxu** [comment]
Ah, not sure if this is an issue caused by windows or not, I'll check it later on a Windows machine and thanks for reporting!

**Comment by maquchizi** [comment]
@binggg Which version of node are you using? This could be an issue with the node version. Had the same error but upgraded to the latest stable version and this works just fine. cc @fraserxu

**Comment by reagle** [comment]
I got this too on Kubuntu 14.04 .

**Comment by julmis** [comment]
Is there any fix on this?
Ubuntu 14.04.4 LTS
```
child_process.js:909
      throw new TypeError('Incorrect value for stdio stream: ' + stdio);
            ^
TypeError: Incorrect value for stdio stream: inherit
    at child_process.js:909:13
    at Array.reduce (native)
    at ChildProcess.spawn (child_process.js:864:17)
    at exports.spawn (child_process.js:723:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/cli.js:9:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by riteme** [comment]
Node.js on Ubuntu is too old. Its version is V0.10.X.
I have tested it and got the same error.
You can download Node.js from its offical website (V4.5.0 and V6.4.0 both tested), `electron-pdf` works on them.

However, `electron-pdf` works correctly when I convert specified files.
When I just input:

```shelll
electron-pdf
```

with no arguments, I got this error below:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1433:5)
    at isMarkdown (/usr/local/lib/node_modules/electron-pdf/index.js:39:20)
    at App.appReady (/usr/local/lib/node_modules/electron-pdf/index.js:43:7)
    at emitOne (events.js:101:20)
    at App.emit (events.js:188:7)
```

**Comment by codecounselor** [comment]
old/non-issue
