### ISSUE TITLE
Not working on Linux/Ubuntu 16.04

### ISSUE THREAD

**Issue by eddydarell** [fraserxu/electron-pdf#138]
I have installed electron-pdf via npm as specified in the README file. But when I run `electron-pdf --help` I get this error:

`internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/cli.js:10:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
`

**Comment by fraserxu** [comment]
This looks like a permission issue, can you try run it with `sudo`?

**Comment by eddydarell** [comment]
Thanks for a quick answer.
I have tried and it works fine from the CLI but I would like to run it from PHP using something like this:

`$cmd = 'electron-pdf --help';`
`$response = shell_exec($cmd);`

Am I missing something?

**Comment by fraserxu** [comment]
I don't know much about PHP but you might need to pass the full path of the binary file so it can find it. You can try `which electron-pdf` from the terminal first.

**Comment by eddydarell** [comment]
It still does not work. I think it is important to mention that before I get this error, I get this one first:

return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/electron-pdf/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

But then I create an empty file called `path.txt` in the right directory and then I get this late error instead:

internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/cli.js:10:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)

**Comment by fraserxu** [comment]
If it works in CLI which means the tools should be able to run on that system, as for the `spawn EACCES` error, it's surly a permission error. You might need to either run it with `sudo` or change the permission of either `electron-pdf` binary file or the php server by running `chmod 777 FILENAME`.

**Comment by eddydarell** [comment]
Still doesn't work. Not event in the CLI and I have don 

`sudo chmod -R 777 electron-pdf`

To give all necessary permissions, yet I get the same error message.
I've read around a little and every solution talks about permissions (which I have done.) and now I'm really desperate. I have no idea where the problem can be. :cry:

**Comment by eddydarell** [comment]
Hello, I was able to get electron-pdf to work on CentOS 7 without any problem and believe this is an issue with my Ubuntu 16.04 installation.

But I have a feature request: Is it possible to add an option to return the PDF as a buffer via STDOUT or as a Base64 string that could be directly consumed by a script like PHP to skipped writing the document on the disk?

Thank you for a great tool by the way.

**Comment by codecounselor** [comment]
@eddydarell I suppose that could be done, but I'm not sure when @fraserxu or I will get around to implementing it.  Feel free to log an issue for a feature request.  A PR would be even better :) 
Glad to hear you resolved your issue and are finding electron-pdf useful.

**Comment by codecounselor** [comment]
Not an issue with electron-pdf, closing.
