### ISSUE TITLE
Error running command line example

### ISSUE THREAD

**Issue by greenlaw110** [fraserxu/electron-pdf#142]
Following the README.md file, I run `electron-pdf https://fraserxu.me ~/Desktop/fraserxu.pdf` and I got the error showing below:

```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/electron-pdf/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by hay** [comment]
Yup, same problem here.

**Comment by fraserxu** [comment]
Can you tell us what's the node.js version you are using and what system you are running on?

**Comment by codecounselor** [comment]
I don't know if it will solve your problem, but you could try installing NVM (node version manager), and if you're on a mac use homebrew because it will put everything in your user space (no sudo).  That might clear up any permission related problems.

**Comment by codecounselor** [comment]
I also just found this: https://github.com/electron/electron/issues/3563. 
I'm running Node 6.7 on a OSX 10.12.1 and I can not reproduce the error, but I also don't normally install/run electron-pdf globally.

**Comment by greenlaw110** [comment]
@fraserxu my node version is v4.2.6

**Comment by codecounselor** [comment]
I think its probably more a function of your OS and/or NPM version or install location.  
Electron comes with its own version of node (currently 6.5.0)

If you're on a mac, can you try install nvm with homebrew and see if that resolves your issue?
Alternatively, you could clone the git repo and then do this in the project directory:
```
npm install
./cli.js ./README.md readme.pdf
```

That will run everything relative to the project and should rule out any global npm or permission issues.

**Comment by codecounselor** [comment]
no activity, please reopen and provide update if help is still needed
