### ISSUE TITLE
TypeError: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by steric85** [fraserxu/electron-pdf#195]
I am trying to use `electron-pdf` to create PDFs using Node. For doing so I used the code given by @midweststudios at [Issue #138](https://github.com/fraserxu/electron-pdf/issues/183). On doing `npm start` I am getting the following error:
```
/Users/a/makePDF/node_modules/electron-pdf/lib/index.js:45
electronApp = electron.app;
                      ^
TypeError: Cannot read property 'app' of undefined
    at start (/Users/a/makePDF/node_modules/electron-pdf/lib/index.js:45:49)
    at Object.<anonymous> (/Users/a/makePDF/index.js:7:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```
Inshort, I am unable to import `electron`. Logging the value of electron gives a path :
`/Users/a/makePDF/node_modules/electron-pdf/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron`
You can see my code in [my github repo](https://github.com/steric85/makePDF).
I tried using `const electron = require('electron').remote` instead `const electron = require('electron')` , but that doesn't work either. Please help me in fixing this.
Thanks in advance 😄

**Comment by codecounselor** [comment]
My guess is your code is getting invoked before things are setup.  There is a `charged` event that is emitted for this purpose.  I'm using express, and so I listen for this event before starting the server.
```
const app = express()
exporter.on('charged', () => {
  app.listen(PORT, HOSTNAME, function () {
    logger(`Export Server running at http://${HOSTNAME}:${PORT}`)
  })
})
```
You should be able to replace `app.listen` with the contents of your IIFE

**Comment by midweststudios** [comment]
@steric85 I looked at your github repo code. In your root `index.js` file, it appears you're not starting the Electron process. My provided modifications in #183 assumes the minimum Electron processes are currently taking place:
- The Electron application is initialized and ready through the app's **main process**
- The **main process** must create a BrowserWindow that renders a web page (i.e. index.html), this is called the **renderer process**

Please refer to the [electron-quick-start](https://github.com/electron/electron-quick-start) repository for instructions on how to setup a basic Electron application. 

In this example, you will need to copy the code from [your github repo](https://github.com/steric85/makePDF/blob/master/index.js) `index.js` file to the now locally installed/cloned [electron-quick-start](https://github.com/electron/electron-quick-start) `renderer.js` file located in the projects root directory.

**Comment by riezebosch** [comment]
I also use this package from a node application. My workaround is currently spawning this package in a child process (which spawns electron). But a better api from node would be appreciated.

**Comment by codecounselor** [comment]
My application is only used to perform exports, so I run it with Electron.  Electron is packaged with it's own version of Node and so I think this makes the most sense.  Have you considered separating out an export server?  I can work on publishing a reference implementation for this if anyone is interested.  

Otherwise I'm open to a PR to enhance the electron-pdf to essentially spin up and do a single export from inside a node process.  I think all you'd be doing though is encapsulating the child process, because I don't see a way to avoid that.

**Comment by midweststudios** [comment]
@riezebosch Electron actually has a really good `.printToPDF()` method within their [web-contents](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsprinttopdfoptions-callback) API (the [`<webview>`](https://github.com/electron/electron/blob/master/docs/api/webview-tag.md#webviewprinttopdfoptions-callback) tag, similiar to an `<iframe>` but runs in a separte process and is more safe, uses the same methods) and if I remember correctly, this tool includes it in the source code for generating the PDFs. I have since switched to using the native Electron `.printToPDF()` method (I did not previously know of it's existence when I found this API), but am overall very pleased with the functionality of this tool.

**Comment by md2perpe** [comment]
I think that the problem here is that `require('electron')` in [`node_modules/electron-pdf/lib/index.js`](https://github.com/steric85/makePDF/blob/master/node_modules/electron-pdf/lib/index.js) resolves to a [module just exporting a string](https://github.com/steric85/makePDF/blob/master/node_modules/electron/index.js).

I got the same problem today when npm downloaded [this](https://registry.npmjs.org/electron/-/electron-1.4.16.tgz) package for electron. Why does this happen and how can it be resolved?
