### ISSUE TITLE
Error: Xlib:  extension "RANDR" missing on display ":99.0"?  when runned in a docker container!!

### ISSUE THREAD

**Issue by mohanzeal** [fraserxu/electron-pdf#214]
more error log...
Xlib:  extension "RANDR" missing on display ":99.0".
App threw an error during load
Error: Cannot find module 'minimist'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/lib/charge.js:1:174)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/lib/charge.js:43:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'minimist'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/lib/charge.js:1:174)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-pdf/lib/charge.js:43:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
Xlib:  extension "RANDR" missing on display ":99.0".
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted

any idea?

**Comment by fraserxu** [comment]
> Error: Cannot find module 'minimist'

It could be there are network errors that it failed to install some of the dependencies.

**Comment by mohanzeal** [comment]
i was running electron pdf in a docker container .. i was able to fix this Error: Cannot find module 'minimist'
but  **Xlib: extension "RANDR" missing on display ":99.0"**  error still persists

**Comment by fraserxu** [comment]
`Xlib: extension "RANDR" missing on display ":99.0"` looks like another dependencies issue, you may check this example and see if you are missing any dependencies https://github.com/fraserxu/docker-tape-run It's in the readme about how to run it with docker by the way.

**Comment by mohanzeal** [comment]
@fraserxu  **thanks** for the quick help .. I was able to solve the problem. PDF is generating.. but the errors persists:
Xlib:  extension "RANDR" missing on display ":99".
Xlib:  extension "RANDR" missing on display ":99".
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

**below command did the work**
`xvfb-run  electron-pdf http://google.com abc.pdf -p A4 -m 2`

is there any way to turn off the error/warning reporting? Eventually I have to validate programatically weather pdf is getting generated or not.  

thanks again for the quick help..

**Comment by fraserxu** [comment]
Sorry I haven't get the same error as you have here before. But it still looks like a dependencies issue for me. I suggest you to Google those error message.
