### ISSUE TITLE
Permission issue while running electron-pdf with www-data

### ISSUE THREAD

**Issue by hatemben** [fraserxu/electron-pdf#247]
Hello,

I'm trying to run electron-pdf from a PHP web app, the problem that if I run the command using my user it works, but if I run it using www-data I get this error then it hangs :

`www-data@hatem-Desktop2:~/html/web$ xvfb-run --auto-servernum electron-pdf /tmp/5cbea59fcd35e2.48316272.html /tmp/5cbea59fcd3521.23588439.pdf --browserConfig '{ "webPreferences": { "sandbox" : true } }'
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to get 'appData' path
    at Object.<anonymous> (/usr/lib/node_modules/electron-pdf/node_modules/electron/dist/resources/electron.asar/browser/init.js:148:39)
    at Object.<anonymous> (/usr/lib/node_modules/electron-pdf/node_modules/electron/dist/resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
`

From the browser it will only hangs, I had to switch to www-data to be able to see the error. For info my user's groups : 

`$id hatem
uid=1000(hatem) gid=1000(hatem) groups=1000(hatem),0(root),4(adm),24(cdrom),27(sudo),30(dip),33(www-data),46(plugdev),113(lpadmin),128(sambashare),999(docker)`

and www-data ones : 

`$ id www-data
uid=33(www-data) gid=33(www-data) groups=33(www-data)`

Electron-pdf v4.0.5
Ubuntu 18.04.2 LTS

Any suggestion thank you !

**Comment by hatemben** [comment]
Fixed by adding this line to $sudo visudo

www-data ALL = NOPASSWD: /usr/bin/xvfb-run
