### ISSUE TITLE
commandLine of undefined

### ISSUE THREAD

**Issue by Liberateur** [fraserxu/electron-pdf#269]
Hey hi !

Does this module still work?

I have one file : test.js
```
// Get modules
const pdf = require('electron-pdf');

// Start pdf exporter
var exporter = new pdf();

// Async instance and await loaded
exporter.on('charged', () =>
{
  console.log('yeah');
});
exporter.start();
```

When i run it `$ node test.js` :
```
/XXX/node_modules/electron-pdf/lib/index.js:97
    electronApp.commandLine.appendSwitch('disable-renderer-backgrounding')
                ^

TypeError: Cannot read property 'commandLine' of undefined
    at PDFExporter.configureElectron (/XXX/node_modules/electron-pdf/lib/index.js:97:17)
    at PDFExporter.start (/XXX/node_modules/electron-pdf/lib/index.js:47:10)
    at Object.<anonymous> (/XXX/test.js:42:10)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

```
Node v14.2.0 (and i have try with 12.5)
```

I tried install/uninstall electron and electron-pdf, same error.

This command line work `$ electron-pdf index.html ~/Desktop/index.pdf`, but I want to generate many pdf, so without having to relaunch electron on each pdf ....

**Comment by codecounselor** [comment]
You can't run the process with Node, you have to invoke it with Electron.  That's why the CLI works (look at cli.js)

This will work:
> ./node_modules/.bin/electron test.js
yeah

And in the readme notice `electron` in the npm tasks
![image](https://user-images.githubusercontent.com/12678528/82232301-775d3880-98fc-11ea-8b2e-6d0e68ae3edc.png)
