### ISSUE TITLE
Error everytime I run electron-pdf

### ISSUE THREAD

**Issue by n-marshall** [fraserxu/electron-pdf#57]
I get ths error everytime I run electron-pdf :

```
App threw an error when running [TypeError: Cannot read property 'on' of undefined]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/electron-pdf/index.js:27:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/usr/lib/node_modules/electron-pdf/node_modules/electron-prebuilt/dist/resources/default_app/main.js:252:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Even when running electron-pdf without any paramters, I get this error (but I get the manual printed in the console fine after that).
When trying to convert a html file, I get only this error and no output file is written.

Nothing critical for me, I just thought I should report this.

**Comment by codecounselor** [comment]
Fixed in #104
